### ISSUE TITLE
Make state publicly available?

### ISSUE THREAD

**Issue by mattyohe** [willowtreeapps/cordux#11]
https://github.com/willowtreeapps/cordux/blob/develop/Sources/Store.swift#L24

Is there a reason that `Store`'s state is not publicly accessible?

**Comment by mattyohe** [comment]
More specifically: State being available only need it accessible to read not set. So:
```swift
public private (set) var state: State
```

**Comment by mattyohe** [comment]
Hmm, we'd have to protect reading/writing access however...

**Comment by ianterrell** [comment]
The intention was to have a single point of access for reading (subscriptions) and for writing (reducers). But the latter is significantly more important than the former. I can't think of a good reason to deny public read access.
