### ISSUE TITLE
Cordux doesn't compile in Swift 3.1

### ISSUE THREAD

**Issue by AndrewSB** [willowtreeapps/cordux#39]
It looks like something Apple changed with the `Sequence` protocol in their latest _non-breaking_ [release](https://swift.org/blog/swift-3-1-released/)

<img width="1440" alt="screen shot 2017-03-29 at 11 01 25 pm" src="https://cloud.githubusercontent.com/assets/3814772/24489699/d950aeb0-14d3-11e7-9789-d9e2c4fb1ab9.png">

**Comment by mattyohe** [comment]
@AndrewSB are you sure you are using a non-beta version of Xcode 8.3? This was indeed an issue in beta 2.

**Comment by AndrewSB** [comment]
I'm pretty sure, I'm on the latest Xcode downloaded from the Mac App Store.
So far apple has only been bending stable releases from the App Store

**Comment by AndrewSB** [comment]
Bump

It looks like `Sequence` was tweaked in the 3.1 release (https://swift.org/blog/swift-3-1-released/). It seems as if it's related to that

**Comment by ianterrell** [comment]
I'm looking at this today.

**Comment by ianterrell** [comment]
@AndrewSB As best I can tell this is a compiler regression. I hadn't noticed it because we're building Cordux in Release mode, which works! When whole module optimization is turned on this issue is not present.

I've pushed up a commit that adds WMO to the Debug configuration; let me know if that does not resolve the issue for you.

I've filed an issue at https://bugs.swift.org/browse/SR-4478 and will keep an eye on it to see if I can create a better solution in the future.

**Comment by AndrewSB** [comment]
Hmmm, if I could get release builds working that would be awesome! They seem to be failing for me (at least through `carthage`) when I use `-configuration Release`

```
*** Building scheme "Cordux-iOS" in Cordux.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/asb/Developer/wrytr/Carthage/Checkouts/cordux/Cordux.xcodeproj -scheme Cordux-iOS -configuration Release -derivedDataPath /Users/asb/Library/Caches/org.carthage.CarthageKit/DerivedData/cordux/v0.1.10 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/7z/4mcv8mgj0sn_dpknz35k7z0w0000gn/T/carthage-xcodebuild.phr8jn.log
```

I can paste the full xcodebuild log as well, but the errors Im getting are similar to the ones Xcode was giving me in the screenshot above

**Comment by ianterrell** [comment]
What version is that trying to build? You can see it in `Cartfile.resolved`. We're having no trouble building with 8.3 in release mode.

We're building v0.2.19: `github "willowtreeapps/cordux" "v0.2.19"`

**Comment by AndrewSB** [comment]
yup, that fixed my issue. Sorry about wasting your time by missing something that trivial @ianterrell

**Comment by ianterrell** [comment]
No apology necessary! :)
